import { Document, Paragraph, TextRun, HeadingLevel, Packer } from 'docx';
import pptxgen from 'pptxgenjs';
import { jsPDF } from 'jspdf';
import { StructuredContent, TransformationType } from '../../src/types/index.js';

export interface ExportPayload {
  title: string;
  format: 'txt' | 'md' | 'docx' | 'pdf' | 'pptx';
  content: string;
  structuredJson?: StructuredContent;
  transformationType?: TransformationType;
}

/**
 * Generate a DOCX document from content
 */
export async function generateDocxBuffer(title: string, content: string, structured?: StructuredContent): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({
      text: title || 'TransformAI Generated Document',
      heading: HeadingLevel.TITLE,
      spacing: { after: 300 },
    }),
  ];

  if (structured?.summary) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Executive Summary', bold: true, size: 28 }),
        ],
        spacing: { before: 200, after: 120 },
      }),
      new Paragraph({
        text: structured.summary,
        spacing: { after: 240 },
      })
    );
  }

  if (structured?.sections && structured.sections.length > 0) {
    for (const sec of structured.sections) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: sec.heading, bold: true, size: 24 }),
          ],
          spacing: { before: 200, after: 100 },
        }),
        new Paragraph({
          text: sec.content,
          spacing: { after: 140 },
        })
      );

      if (sec.bullets && sec.bullets.length > 0) {
        for (const b of sec.bullets) {
          children.push(
            new Paragraph({
              text: `• ${b}`,
              spacing: { after: 60 },
            })
          );
        }
      }
    }
  } else {
    // Fallback: parse lines from content
    const lines = content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      if (trimmed.startsWith('# ')) {
        children.push(new Paragraph({ text: trimmed.replace(/^#\s*/, ''), heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }));
      } else if (trimmed.startsWith('## ')) {
        children.push(new Paragraph({ text: trimmed.replace(/^##\s*/, ''), heading: HeadingLevel.HEADING_2, spacing: { before: 180, after: 80 } }));
      } else if (trimmed.startsWith('### ')) {
        children.push(new Paragraph({ text: trimmed.replace(/^###\s*/, ''), heading: HeadingLevel.HEADING_3, spacing: { before: 140, after: 60 } }));
      } else {
        children.push(new Paragraph({ text: trimmed, spacing: { after: 100 } }));
      }
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

/**
 * Generate a PPTX presentation from structured slide data
 */
export async function generatePptxBuffer(title: string, structured?: StructuredContent, rawContent?: string): Promise<Buffer> {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';
  pptx.author = 'TransformAI';
  pptx.company = 'TransformAI Platform';

  // Title Slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: '0F172A' }; // Slate 900
  titleSlide.addText(title || 'TransformAI Presentation', {
    x: '10%',
    y: '35%',
    w: '80%',
    h: '20%',
    fontSize: 36,
    bold: true,
    color: 'FFFFFF',
    align: 'center',
    fontFace: 'Arial',
  });
  titleSlide.addText('Generated by TransformAI • Platform for Automated Content Transformation', {
    x: '10%',
    y: '58%',
    w: '80%',
    h: '10%',
    fontSize: 16,
    color: '94A3B8',
    align: 'center',
    fontFace: 'Arial',
  });

  if (structured?.slides && structured.slides.length > 0) {
    for (const slideData of structured.slides) {
      const slide = pptx.addSlide();
      slide.background = { color: 'F8FAFC' };

      // Header Bar
      slide.addText(slideData.title, {
        x: '8%',
        y: '8%',
        w: '84%',
        h: '14%',
        fontSize: 24,
        bold: true,
        color: '0F172A',
        fontFace: 'Arial',
      });

      // Bullets
      if (slideData.bullets && slideData.bullets.length > 0) {
        const bulletObjects = slideData.bullets.map((b) => ({
          text: b,
          options: {
            bullet: true,
            fontSize: 16,
            color: '334155',
            breakLine: true,
          },
        }));

        slide.addText(bulletObjects, {
          x: '8%',
          y: '26%',
          w: '84%',
          h: '55%',
          margin: 0.1,
          fontFace: 'Arial',
        });
      }

      // Speaker Notes
      if (slideData.speakerNotes) {
        slide.addNotes(slideData.speakerNotes);
      }
    }
  } else {
    // Fallback: create slides from sections or paragraphs
    const slide = pptx.addSlide();
    slide.background = { color: 'F8FAFC' };
    slide.addText(title || 'Key Insights', {
      x: '8%',
      y: '8%',
      w: '84%',
      h: '14%',
      fontSize: 24,
      bold: true,
      color: '0F172A',
    });
    slide.addText(rawContent?.slice(0, 1000) || 'Presentation Content', {
      x: '8%',
      y: '26%',
      w: '84%',
      h: '60%',
      fontSize: 14,
      color: '334155',
    });
  }

  // Final Summary Slide
  const endSlide = pptx.addSlide();
  endSlide.background = { color: '0F172A' };
  endSlide.addText('Summary & Next Steps', {
    x: '10%',
    y: '30%',
    w: '80%',
    h: '15%',
    fontSize: 32,
    bold: true,
    color: 'FFFFFF',
    align: 'center',
  });
  endSlide.addText('Generated with TransformAI • One Source. Infinite Transformations.', {
    x: '10%',
    y: '50%',
    w: '80%',
    h: '10%',
    fontSize: 16,
    color: '94A3B8',
    align: 'center',
  });

  const arrayBuffer = (await pptx.write({ outputType: 'nodebuffer' })) as Buffer;
  return arrayBuffer;
}

/**
 * Generate a PDF document from content
 */
export async function generatePdfBuffer(title: string, content: string): Promise<Buffer> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const maxLineWidth = pageWidth - margin * 2;

  // Title Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text(title || 'TransformAI Document', margin, 50);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('Transformed with TransformAI • Content Transformation Platform', margin, 70);

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, 80, pageWidth - margin, 80);

  // Body content
  let cursorY = 105;
  const lines = content.split('\n');

  doc.setTextColor(51, 65, 85);

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      cursorY += 10;
      continue;
    }

    if (cursorY > 780) {
      doc.addPage();
      cursorY = 50;
    }

    if (trimmed.startsWith('# ')) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      cursorY += 12;
      doc.text(trimmed.replace(/^#\s*/, ''), margin, cursorY);
      cursorY += 18;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(51, 65, 85);
    } else if (trimmed.startsWith('## ') || trimmed.startsWith('### ')) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(30, 41, 59);
      cursorY += 8;
      doc.text(trimmed.replace(/^#+\s*/, ''), margin, cursorY);
      cursorY += 14;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(51, 65, 85);
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const splitLines = doc.splitTextToSize(trimmed, maxLineWidth);
      for (const sl of splitLines) {
        if (cursorY > 790) {
          doc.addPage();
          cursorY = 50;
        }
        doc.text(sl, margin, cursorY);
        cursorY += 14;
      }
    }
  }

  const pdfOutput = doc.output('arraybuffer');
  return Buffer.from(pdfOutput);
}
